### PR TITLE
Fix logic bug where things that aren't gzipped were being un-gzipped

### PR DESCRIPTION
**Pull request by thisisaaronland**
* fix logic bug where things that aren't gzipped were being un-gzipped
* add .db files to .gitignore
* update Go modules

### CODE REVIEW

**Comment by iandees** [comment]
I think I did this on purpose to do "distributed gzipping" when scraping tiles to mbtiles. This change is good, but can you double-check the mbtiles write side to make sure I'm gzipping when the gzip flag is set? If memory serves I am writing whatever bytes I get on the channel and assuming they're gzipped. If it's not a simple change we can merge this and file a new ticket to fix that later.

**Comment by thisisaaronland** [comment]
@iandees - I checked with this (https://github.com/whosonfirst/go-whosonfirst-fileserver#www-fileserver) and the gzip-ing is only happening when the `-H "Accept-Encoding: gzip"` is present.

**Comment by thisisaaronland** [comment]
Oh, I guess I got pull requests mixed up. So there's now a second PR combined with this one that:

* Add a new `tilepack.NewFileTransportXYZJobGenerator` method and corresponding `cmd/build` flags to allow URL templates to use `file://` URLs to indicate source data is local
* Add a new `tilepack.HTTPError` error class that is used by `doHTTPWithRetry` and returned if errors are >= 500 and <= 600. This makes error reporting more precise, since these are errors that will never be retried.

**Comment by thisisaaronland** [comment]
☝️ also, those last two commits to prevent file handle exhaustion and panic-ing respectively.

**Comment by nvkelso** [comment]
@thisisaaronland Is this ready for @iandees to review now?

**Comment by thisisaaronland** [comment]
Yup.

**Review by iandees — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
