### PR TITLE
Update to use Go modules

### PR DESCRIPTION
**Pull request by thisisaaronland**
* Replaces `gopkg` stuff with `go mod` stuff since the latter is the default/built-in dependency system as of 1.12
* Add a `Makefile` for building tools in local `bin` directory (which is excluded from commits)
* Update `.gitignore` file to exclude Emacs `~` files

Personally I have no feelings about package/dependency managers beyond "If Go is going to settle this for everyone, as with `go fmt` then I am okay with it".

Go modules depend on things having `v{X}.{Y}.{Z}` semantic tags/releases so this package should probably start minting releases too, in the interest of playing nice with others.

### CODE REVIEW

**Comment by nvkelso** [comment]
@zerebubuth can you have a look at this PR since Ian is away?

**Comment by iandees** [comment]
I started this using `dep`, which I thought was the preferred way of doing dependencies with Go nowadays.

**Comment by zerebubuth** [comment]
Yeah, I thought that `dep` was the current / future preferred way too. But looking at [their README](https://github.com/golang/dep/blob/821796cfc8e066fe63a0174487d7faafd043996b/README.md#dep):

> `dep` was the "official experiment." The Go toolchain, as of 1.11, has adopted an approach that sharply diverges from `dep`. 

So... I guess that means that this week the official preferred way is `go mod`? What do you think, @iandees?

**Comment by iandees** [comment]
Sounds good to me. Guess I should read more about go modules then :)

**Comment by zerebubuth** [comment]
Great, thanks!

**Review by zerebubuth — APPROVED** [review]
Looks good to me, thanks!

**Pull request merged**
